install_deps: add curtin
canonical/subiquity pull request #1019
Opened 2021-08-04 12:02 UTC by jpnurmi

On a clean system running subiquity_client tests would throw

    ModuleNotFoundError: No module named 'curtin'

2021-08-04 15:39 UTC, dbungert commented
@jpnurmi
Curtin in the archive will usually not be the version that we want.
`make gitdeps` will grab the exact curtin/probert.
`make install_deps` probably doesn't even need probert at this point.

What if we do this:
* subiquity: `make install_deps` depends on `make gitdeps`
* u-d-i: use pythonpath to point to the curtin & probert subdirectories that get created by `make gitdeps`

2021-08-04 16:07 UTC, dbungert requested changes

2021-08-04 16:07 UTC, dbungert commented on Makefile
> +		curtin
By itself this is fine, but see comment for why I think this isn't what you want.

2021-08-05 08:39 UTC, jpnurmi commented
Thanks, I hadn't even noticed the `gitdeps` target. The installer's instructions listed `make install_deps` so I was used to running that.

Personally, I would be fine setting up `PYTHONPATH`, but I wonder how we could make it as convenient as possible for external contributors. There are no makefiles in u-b-i, but Flutter devs will open the project in IDE, hit the run button, and wonder why things don't work.

2021-08-05 08:42 UTC, jpnurmi commented
Hmm, looks like the CI runs `make install_deps && sudo apt install python3-curtin`, so it could start failing if `curtin` is outdated.

https://github.com/canonical/ubuntu-desktop-installer/blob/main/.github/workflows/flutter-ci.yml#L37

2021-08-05 14:25 UTC, dbungert commented
Yes, we will need to ensure that your CI command can get dependencies, and that it's easy for flutter contributors to work with.
The makefile dependency I mention above should get the right version of curtin/probert for these use cases, without having to adjust your install instructions or change your CI config.
As far as PYTHONPATH, I suppose we could set environment variables in app.dart before invoking subiquity.  In the snap this is handled already with the wrapper script.
What do you think?

2021-08-05 20:38 UTC, jpnurmi commented
Thanks, I misunderstood the original proposal. This approach works indeed. :)

2021-08-05 20:59 UTC, dbungert approved these changes

2021-08-05 21:00 UTC, merged

2021-08-12 13:11 UTC, jpnurmi commented
This didn't work as expected. Should it be reverted? Also, would it be better to start using `scripts/installdeps.sh` like in the CI?

2021-08-12 13:28 UTC, jpnurmi commented
Ohh, sorry. I haven't actually tried the latest main.

I went straight for `installdeps.sh` this time because of the dependency issue we saw in the CI. Wasn't it so that gitdeps depends on libsomething-dev, which is installed by install_deps?