install source selection
canonical/subiquity pull request #1030
Opened 2021-08-19 04:58 UTC by mwhudson

This is going to be hard to test until there is an image made with the livecd-rootfs change I just uploaded which won't happen for a day or two I guess but someone can read the code at least :)

2021-08-19 20:00 UTC, dbungert requested changes

2021-08-19 22:33 UTC, mwhudson commented on subiquity/server/controllers/filesystem.py
> +        min_size = 2*self.app.base_model.source.current.size + (1 << 30)
Ah you mean, the min size should be in the catalog? that might make sense yes...

2021-08-19 22:34 UTC, mwhudson commented on subiquity/models/source.py
> +                'ubuntu00': '{scheme}://{path}'.format(
no not really. I've been programming Python too long to pick up these new-fangled things quickly :)

2021-08-19 22:35 UTC, mwhudson commented on subiquity/ui/views/source.py
> +                size = humanize_size(align_up(source.size, 2 << (i-3)))
Oh yes, this bit is all a bit hackish. I meant to pull it out into a shared and tested function before review...

I don't think we have to be _too_ worried about the catalog being wrong, I mean we're pretty dependent on the path in it being correct, but validating that size is strictly positive is probably a good idea.

2021-08-19 22:40 UTC, mwhudson commented on subiquity/server/controllers/source.py
> +    async def GET(self) -> SourceSelectionAndSetting:
the source endpoint is only interactive if there is more than one source in the catalog. So if you get curl to dump headers, you should see x-override-status: skip here.

2021-09-01 04:51 UTC, mwhudson commented
FWIW you can play with this with the impish dailies now.

2021-09-03 15:23 UTC, dbungert commented on subiquity/ui/views/source.py
> +                size = humanize_size(align_up(source.size, 2 << (i-3)))
on second thought - does this cause more problems than it solves to show a number here?
The UI claims that the minimized will only take 512MiB, but a crude df on the result puts it at 6GiB
Non-minimized claims 1GiB/6.4GiB actual.
Can we proactively explain the difference?

2021-09-03 15:35 UTC, dbungert commented on subiquity/ui/views/source.py
> +                size = humanize_size(align_up(source.size, 2 << (i-3)))
those numbers include 4GiB swap file, btw.
TIL /usr/lib/firmware is 700MiB+.

2021-09-13 01:18 UTC, mwhudson commented on subiquity/server/controllers/filesystem.py
> +        min_size = 2*self.app.base_model.source.current.size + (1 << 30)
I've put a comment in the code about this. I'd like to move forward with this work if you trust me to not forget about coming back to this...

2021-09-13 01:19 UTC, mwhudson commented on subiquity/ui/views/source.py
> +                size = humanize_size(align_up(source.size, 2 << (i-3)))
I've just dropped displaying a number here for now.

2021-09-13 01:20 UTC, mwhudson commented
So I've just rebased this to simplify it a bit and also add some tests. Let me know what you think!

2021-09-13 01:24 UTC, dbungert commented on subiquity/server/controllers/filesystem.py
> +        min_size = 2*self.app.base_model.source.current.size + (1 << 30)
I trust you :)

2021-09-13 01:26 UTC, dbungert commented on subiquity/ui/views/source.py
> +                size = humanize_size(align_up(source.size, 2 << (i-3)))
Sorry, I really like having the number, I just was dreading the bug report claiming that it was lies.

2021-09-13 01:36 UTC, dbungert approved these changes

2021-09-14 03:10 UTC, mwhudson commented on subiquity/ui/views/source.py
> +                size = humanize_size(align_up(source.size, 2 << (i-3)))
Yeah we should probably display something. For the next branch!

2021-09-14 03:11 UTC, merged