configure apt before starting install
canonical/subiquity pull request #1123
Opened 2021-11-10 10:49 UTC by mwhudson

Via lots of overlays.

2021-11-10 10:50 UTC, mwhudson commented
TBH this is mostly a request for opinions. It works, I think (haven't checked exactly this version in a VM but I have had something similar working) and it should provide a base for doing interesting ubuntu-drivers ish things.

2021-11-15 23:47 UTC, dbungert requested changes
Code is fine bug a test run with autoinstall crashes:

```
2021-11-15 23:44:45,707 ERROR root:39 finish: subiquity/Install/install/postinstall/restore_apt_config: FAIL: 'AptConfigurer' object has no attribute 'curtin_runner'
2021-11-15 23:44:45,708 ERROR root:39 finish: subiquity/Install/install/postinstall: FAIL: 'AptConfigurer' object has no attribute 'curtin_runner'
2021-11-15 23:44:45,708 DEBUG subiquitycore.common.errorreport:384 generating crash report
2021-11-15 23:44:45,709 INFO subiquitycore.common.errorreport:406 saving crash report 'install failed crashed with AttributeError' to /var/crash/1637019885.708616972.install_fail.crash
2021-11-15 23:44:45,709 ERROR root:39 finish: subiquity/Install/install: FAIL: 'AptConfigurer' object has no attribute 'curtin_runner'
2021-11-15 23:44:45,709 INFO root:39 start: subiquity/ErrorReporter/1637019885.708616972.install_fail/add_info: 
2021-11-15 23:44:45,709 ERROR subiquity.server.server:393 top level error
Traceback (most recent call last):
  File "/snap/subiquity/x1/lib/python3.8/site-packages/subiquity/server/controllers/cmdlist.py", line 104, in _run
    await Install.install_task
  File "/snap/subiquity/x1/lib/python3.8/site-packages/subiquitycore/context.py", line 148, in decorated_async
    return await meth(self, **kw)
  File "/snap/subiquity/x1/lib/python3.8/site-packages/subiquity/server/controllers/install.py", line 183, in install
    await self.postinstall(context=context)
  File "/snap/subiquity/x1/lib/python3.8/site-packages/subiquitycore/context.py", line 148, in decorated_async
    return await meth(self, **kw)
  File "/snap/subiquity/x1/lib/python3.8/site-packages/subiquity/server/controllers/install.py", line 212, in postinstall
    await self.restore_apt_config(context=context)
  File "/snap/subiquity/x1/lib/python3.8/site-packages/subiquitycore/context.py", line 148, in decorated_async
    return await meth(self, **kw)
  File "/snap/subiquity/x1/lib/python3.8/site-packages/subiquity/server/controllers/install.py", line 231, in restore_apt_config
    await self.apt_configurer.deconfigure(context, self.tpath())
  File "/snap/subiquity/x1/lib/python3.8/site-packages/subiquity/server/apt.py", line 161, in deconfigure
    await self.curtin_runner.run(
AttributeError: 'AptConfigurer' object has no attribute 'curtin_runner'
```

2021-11-16 02:36 UTC, dbungert approved these changes

2021-11-17 01:23 UTC, dbungert approved these changes

2021-11-17 01:36 UTC, merged