Add initial integration of Ubuntu Advantage in Subiquity
canonical/subiquity pull request #1140
Opened 2021-12-08 15:00 UTC by ogayot

Hello,

This PR introduces a new view, model and controllers pair to enable Ubuntu Advantage from Subiquity.
For now, we expect the user to input an alphanumeric token and rely on cloud-init to enable the features associated with the UA subscription.

This implementation comes with a number of limitations:

- inability to validate the token before first-boot
- inability to check what features are associated with the Ubuntu Advantage subscription, before first-boot
- the user must input the token directly: there is no mechanism to deduce the token based on email address and password.

The first patch in the PR is the implementation of the solution. The second patch (that should not be merged as is) draws the new screen right after the welcome screen.

Thanks,
Olivier

2021-12-08 21:13 UTC, dbungert commented
Something in the CI tests went wrong and they were running for 4+ hours.  Please take a peek.  Consider running locally
```
sudo ./scripts/test-in-lxd.sh ubuntu-daily:focal "make check"
```

2021-12-09 02:30 UTC, mwhudson commented
Hi, this looks like a good start. To get the integration tests to work you'll need to add "answers" support to the new client controller and answers to all of the examples/answers*.yaml files (this last bit is not the greatest design). I'm not sure why they are hanging forever though -- they are supposed to time out rather than doing that :(

I do wonder if we want to show this screen when installing a non-LTS?

2021-12-09 08:10 UTC, ogayot commented
Updated to fix the failing integration tests.
I had to squash the two commits together because, for some reason, I didn't manage to have the integration tests succeed with the new screen implemented but not shown.

2021-12-09 13:41 UTC, ogayot commented
> I do wonder if we want to show this screen when installing a non-LTS?

Good point, do we know if non-LTS releases can benefit from some of the components that can be enabled through UA?

2021-12-15 13:28 UTC, ogayot commented
Updated to show screen only when running on LTS version.
In dry-run mode, we always consider that we are on LTS -> we load `examples/lsb-release-focal` instead of `/etc/lsb-release`.

2021-12-15 14:55 UTC, dbungert approved these changes

2021-12-15 21:19 UTC, dbungert requested changes
This is all great!

One change however - we'd like to hide the screen for now.  We'd like to be able to show the screen once we have the ability to validate the token.

2021-12-16 10:22 UTC, ogayot commented
Thanks @Dan!
while implementing the change that you requested, I noticed that raising `Skip` from the client prevented the installation from finishing. 
The reason was that the server-side controller still needs its method `.configured()` to be called to signal that the model has finished configuring. Thanks to @mwhudson for pointing me to the right direction :)

To fix this issue, I created a separate `POST` resource (called skip) to be called by the client when it wants to skip the screen. As a result, to effectively skip the screen, the client must do:

```
# Make sure the server-side controller calls .configured()
await self.endpoint.skip.POST()
raise Skip(...)
```

2021-12-16 23:53 UTC, dbungert approved these changes

2021-12-16 23:53 UTC, dbungert commented on subiquity/client/controllers/ubuntu_advantage.py
> +        if "LTS" not in lsb_release(path_lsb_release)["description"]:
This PR is getting a little long and gathering some additional items, so I want you to do something in a follow-on PR.
We call lsb_release in six spots, and I'd like them to have consistent answers (even in dry-run mode).
So I'd like to add an argument to lsb_release to tell it to use dry-run mode and then that can trigger the usage of the example data.  Then we can tell all lsb_release usage about dryrun.

2021-12-16 23:55 UTC, merged