autoinstall: allow cloud source to override iso source
canonical/subiquity pull request #1237
Opened 2022-03-18 23:01 UTC by dbungert

LP: #1948823

2022-03-21 10:03 UTC, ogayot requested changes
I think we should let Subiquity error if the `--autoinstall` path is specified but does not exist. Falling back to a different autoinstall file if not something I'd expect.

2022-03-21 17:53 UTC, dbungert commented on subiquity/server/server.py
> +            if loc is not None and os.path.exists(loc):
I like this idea, but implemented it somewhat differently.  I wanted to raise an exception for the case that someone has gone to the bother to specify the file as an arg but it was then not found.

2022-03-21 17:57 UTC, ogayot approved these changes

2022-03-21 17:57 UTC, ogayot commented on subiquity/server/server.py
> +            if loc is not None and os.path.exists(loc):
Yes, that works too. Thanks!

2022-03-21 18:19 UTC, dbungert commented on subiquity/server/server.py
> +            if loc is not None and os.path.exists(loc):
It's needed for the most common case, where there is no autoinstall arg at all.  Also, `os.path.exists(None)` raises an exception, so I can't let that handle it.

2022-03-21 18:19 UTC, merged

2022-03-21 18:20 UTC, ogayot commented on subiquity/server/server.py
> +            if loc is not None and os.path.exists(loc):
Oh that's right. My bad.

2022-03-28 01:20 UTC, mwhudson commented
Aaaa I just had a very sudden and late thought which is that we have documented the fact that an early-command can access and edit the autoinstall config at /autoinstall.yaml: https://ubuntu.com/server/docs/install/autoinstall-reference#early-commands

I guess we can put it there just while early-commands are running?