network: fix Wi-Fi interfaces not listed in dry-run
canonical/subiquity pull request #1785
Opened 2023-09-04 11:44 UTC by ogayot

When a Wi-Fi interface is present in the machine configuration (e.g., mwhudson.json), the GUI seemingly ignores it. This happens because there is a filter on the server side which only returns Wi-Fi interfaces if the wlan_support_install_state() function returns
PackageInstallState.DONE.

However, calling the /network endpoint shows that the state is set to the wrong value:

```json
 {"wlan_support_install_state": "NOT_NEEDED"}
```

This turns out to be inconsistent because:
 * we lean on a PackageInstaller instance to tell if wpasupplicant is installed (this is what the wlan_support_install_state() function reflects) ; but
 * in dry-run mode, we pretend to install wpasupplicant without actually relying on the PackageInstaller instance.

Fixed by using the PackageInstaller instance to install the wpasupplicant package - with a special implementation that only pretends to install it. This is enough to make the PackageInstaller instance think the package is installed.

2023-09-04 20:45 UTC, mwhudson requested changes
I think I would rather have a DryRunPackageInstaller class, like we do for CommandRunner. In fact, if we change PackageInstaller to use app.command_runner can we delete a bunch of code??

2023-09-05 11:15 UTC, ogayot commented
> Thanks for this, but I think I would rather have a DryRunPackageInstaller class, like we do for CommandRunner. In fact, if we change PackageInstaller to use app.command_runner can we delete a bunch of code??

Updated. I must admit I don't find these DryRun classes very practical. But I do like that it makes the "main" code cleaner (less cluttered with dry-run specific things).

I had to introduce a little bit of code duplication here, hope it's okay..

2023-09-07 03:33 UTC, mwhudson approved these changes
Sorry for not reviewing yesterday, I did read the code but somehow forgot to write anything down!

This looks OK. I don't think we have to regard the interpretation of SUBIQUITY_DEBUG_FLAGS with any kind of stability though -- seems like it would make things easier and more flexible to switch to using some syntax like SUBIQUITY_DEBUG_FLAGS=pkginstall=wpasupplicant=FAILED or something?

2023-09-07 11:47 UTC, ogayot commented
> Sorry for not reviewing yesterday, I did read the code but somehow forgot to write anything down!
> 
> This looks OK. I don't think we have to regard the interpretation of SUBIQUITY_DEBUG_FLAGS with any kind of stability though -- seems like it would make things easier and more flexible to switch to using some syntax like SUBIQUITY_DEBUG_FLAGS=pkginstall=wpasupplicant=FAILED or something?

Yes that sounds like good improvements to implement going forward :)

2023-09-07 12:06 UTC, merged