apt: Only backup/restore sources.list if it exists
canonical/subiquity pull request #1885
Opened 2024-01-15 16:13 UTC by julian-klode

We backup the sources.list to a file in sources.list.d to be able to insert our source first; if we do not have a sources.list this is not necessary.

If an image uses ubuntu.sources, this logic also works fine as sources.list that we write will be sourced before the ubuntu.sources.

2024-01-15 16:24 UTC, julian-klode commented
Reading this more I'm not sure if this actually deletes the /etc/apt/sources.list with the `cdrom` line, I guess the `_restore_file` is weird and should always succeed or something.

2024-01-15 16:24 UTC, ogayot commented
Related to LP:2026647

2024-01-16 17:25 UTC, ogayot requested changes
Thanks Julian!

> Reading this more I'm not sure if this actually deletes the /etc/apt/sources.list with the `cdrom` line, I guess the `_restore_file` is weird and should always succeed or something.

Yes, the presence of `etc/apt/sources.lists` containing the cdrom entry is unconditional https://github.com/canonical/subiquity/blob/753ce9f7012a526df6deda80ac6a91315b332078/subiquity/server/apt.py#L259-L262

I'm not sure if it would be a huge deal to leave this file on the target system, but for now, I think it's better to keep the current behavior - which means removing the file if it does not exist in the source overlay.

2024-01-16 17:25 UTC, ogayot commented on subiquity/server/apt.py
> +            _restore_file("etc/apt/sources.list")
I think we don't want to keep this file on the target system if it wasn't present in the source overlay. I'd suggest something along these lines:

```python
try:
    _restore_file("etc/apt/sources.list")
except FileNotFoundError:
    os.unlink(target_mnt.p("etc/apt/sources.list"))
```

2024-01-22 12:00 UTC, ogayot approved these changes
I pushed a change to drop sources.list from the target if it wasn't present in the configured tree.

Also added a set of tests for the .deconfigure method.

Marking "Approved" since I requested changes earlier. But it would be fair to get a second approval before merging since I authored some of the changes.

2024-01-23 21:03 UTC, Chris-Peterson444 approved these changes
LGTM!

2024-01-24 00:15 UTC, mwhudson approved these changes
Thanks for this, and for adding tests!

2024-01-24 00:15 UTC, merged