locale - let it check interactive-sections again
canonical/subiquity pull request #937
Opened 2021-04-13 21:29 UTC by dbungert

LP: #1919251

2021-04-13 21:30 UTC, dbungert commented
When this was introduced, the comment was:
  show the initial screen if any screens are interactive
  the idea here is to stop multiple subiquitys from trampling on each other

Is that still relevant?

2021-04-13 22:06 UTC, mwhudson commented
Oh hah I'd forgotten that rationale. No, that's not a valid reason any more -- but there is still one thing I'd like to fix, which is to move the question we ask on the serial console about switching to 'rich mode' somewhere more generic so that it still gets asked even if locale is not interactive. Basically I think this means making a "Stretchy" to ask the question and showing it with add_global_overlay() just after starting the urwid event loop -- if you look at how error reports or cloud-init failures are reported at startup, like that!

2021-04-14 23:09 UTC, mwhudson commented
Very nice, this is exactly what I asked for. Unfortunately (and this is my fault), this does have one regression in functionality though: we probably shouldn't offer a choice of languages in non-rich mode (as most non-English languages will just display as a mess of '?'s). So perhaps instead of being an overlay, the question about rich mode should be its own screen (complete with client/controllers/richmode I guess) that can skip on non-serial. Or we can add some way to skip past the language screen if it's showing when the user selects "continue in basic mode".

What do you think? Sorry to mess you around like this.

2021-04-19 22:33 UTC, mwhudson requested changes
This looks really good thanks! Still have a few comments but nothing deep.

2021-04-19 23:26 UTC, dbungert commented on subiquity/client/client.py
> +            index = 1
Ah, I like that better, good suggestion

2021-04-19 23:38 UTC, dbungert commented on console_conf/controllers/welcome.py
> +        if not self.app.opts.run_on_serial:
Actually, I just noticed this is in console_conf, so I'm reverting this hunk.

2021-04-19 23:44 UTC, dbungert commented
@mwhudson - thanks, all feedback items should be addressed, would you confirm?

2021-04-21 09:44 UTC, mwhudson approved these changes
Thanks, this is great. I guess you might want to rebase or squash merge or something, the history is a bit convoluted. If you can be bothered :)

2021-04-21 16:11 UTC, merged